name: NodeJS Testing
on: [workflow_dispatch, push]
jobs:
    Checkout:
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest]
                node-version: [16, 20.x]
        runs-on: ${{matrix.os}}
        steps:
          - uses: actions/checkout@v3
          - uses: actions/setup-node@v4
            with:
              node-version: ${{matrix.node-version}}
          - name: Download dependencies
            run: npm ci
      #            - name: Build
      #              run: npm run build --if-present
      #            - name: Testing
      #              run: npm test
